### PR TITLE
Iss#23

### PR DESCRIPTION
**Pull request by allegroCoder**
Three new tests added (event logs) (9, 167 and 400 Partial orders) #23

### CODE REVIEW

**Comment by snowleopard** [comment]
@allegroCoder I'm a bit concerned about adding such big tests into the repository. I think it would be better to use generated tests for testing the scalability of encoding methods. Can you generate an example with N = 400 partial orders instead of storing them in a file? This is also more useful, because we can then change the parameter N and obtain a series of tests to see how different encoding methods scale when N increases.

**Comment by allegroCoder** [comment]
Sure, that won't be a problem. What I can do is generating `N` completely random partial orders, with completely random events and arcs. Is it what you have in mind? That might be actually really usefull as a testcase!

**Comment by snowleopard** [comment]
I actually meant a well-defined family of partial orders, so that we all know what we are talking about. For example, first m permutations on n events. For n = 3 and n = 4 we get:
```
1 2 3
1 3 2
2 1 3
2 3 1
```
This can be implemented simply as `take m $ permutations [1..n]` in Haskell :-)

See https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-List.html#v:permutations

Random testing is definitely useful, but should be done using QuickCheck.

**Comment by allegroCoder** [comment]
Looks quite easy with the help of those two function! I will try to implement that :)

**Comment by snowleopard** [comment]
Closing, as it seems abandoned.

**Pull request closed without merging**
